### ISSUE TITLE
Conteo de casos no ponderado

### ISSUE THREAD

**Issue by psirusteam** [inesscc/calidad#1]
Para la estimación de proporciones y tamaños, es muy útil contar con esta medida que permite validar la calidad de la estimación, sobre todo en subpobllaciones y desagregaciones.

Pg 23 de CEPAL
https://www.cepal.org/sites/default/files/publication/files/45681/S2000293_es.pdf

**Comment by inesscc** [comment]
Esto ya está incluido en el estado actual del paquete
